spring:
  datasource:
    url: postgres://effectivemobiledb_user:4d6gGVnxPDSmSUgIBk3ErVAvXsqlO2MD@dpg-cics1u2ip7vnjjmfnofg-a/effectivemobiledb
    username: effectivemobiledb_user
    password: 4d6gGVnxPDSmSUgIBk3ErVAvXsqlO2MD

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 86400000 # a day
      refresh-token:
        expiration: 604800000